version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger.yaml
    environment:
      API_URL: swagger.yaml
    ports:
      - 18080:8080
